interface Event {
  target: Element | undefined;
}

interface MouseEvent extends Event {}
interface DragEvent extends Event {}
interface KeyboardEvent extends Event {}
interface ClipboardEvent extends Event {}
interface CompositionEvent extends Event {}
interface FocusEvent extends Event {}
interface TouchEvent extends Event {}
interface PointerEvent extends Event {}
interface UIEvent extends Event {}
interface AnimationEvent extends Event {}
interface WheelEvent extends Event {}
interface TransitionEvent extends Event {}

interface Node {
  previousSibling: Node;
  nextSibling: Node;
  firstChild: Node;
  lastChild: Node;
}
interface Element extends Node {}
interface HTMLElement extends Element {}
interface SVGElement extends Element {}

interface HTMLAnchorElement extends HTMLElement {}
interface HTMLAudioElement extends HTMLElement {}
interface HTMLAreaElement extends HTMLElement {}
interface HTMLBaseElement extends HTMLElement {}
interface HTMLBlockquoteElement extends HTMLElement {}
interface HTMLButtonElement extends HTMLElement {}
interface HTMLCanvasElement extends HTMLElement {}
interface HTMLColElement extends HTMLElement {}
interface HTMLColgroupElement extends HTMLElement {}
interface HTMLDataElement extends HTMLElement {}
interface HTMLDetailsElement extends HTMLElement {}
interface HTMLDelElement extends HTMLElement {}
interface HTMLDialogElement extends HTMLElement {}
interface HTMLEmbedElement extends HTMLElement {}
interface HTMLFieldsetElement extends HTMLElement {}
interface HTMLFormElement extends HTMLElement {}
interface HTMLHtmlElement extends HTMLElement {}
interface HTMLIframeElement extends HTMLElement {}
interface HTMLImgElement extends HTMLElement {}
interface HTMLInsElement extends HTMLElement {}
interface HTMLInputElement extends HTMLElement {}
interface HTMLKeygenElement extends HTMLElement {}
interface HTMLLabelElement extends HTMLElement {}
interface HTMLLiElement extends HTMLElement {}
interface HTMLLinkElement extends HTMLElement {}
interface HTMLMapElement extends HTMLElement {}
interface HTMLMenuElement extends HTMLElement {}
interface HTMLMediaElement extends HTMLElement {}
interface HTMLMetaElement extends HTMLElement {}
interface HTMLMeterElement extends HTMLElement {}
interface HTMLQuoteElement extends HTMLElement {}
interface HTMLObjectElement extends HTMLElement {}
interface HTMLOlElement extends HTMLElement {}
interface HTMLOptgroupElement extends HTMLElement {}
interface HTMLOptionElement extends HTMLElement {}
interface HTMLOutputElement extends HTMLElement {}
interface HTMLParamElement extends HTMLElement {}
interface HTMLProgressElement extends HTMLElement {}
interface HTMLSlotElement extends HTMLElement {}
interface HTMLScriptElement extends HTMLElement {}
interface HTMLSelectElement extends HTMLElement {}
interface HTMLSourceElement extends HTMLElement {}
interface HTMLStyleElement extends HTMLElement {}
interface HTMLTableElement extends HTMLElement {}
interface HTMLTextareaElement extends HTMLElement {}
interface HTMLTdElement extends HTMLElement {}
interface HTMLThElement extends HTMLElement {}
interface HTMLTimeElement extends HTMLElement {}
interface HTMLTrackElement extends HTMLElement {}
interface HTMLVideoElement extends HTMLElement {}
interface HTMLBodyElement extends HTMLElement {}
interface HTMLBRElement extends HTMLElement {}
interface HTMLTableColElement extends HTMLElement {}
interface HTMLTableColElement extends HTMLElement {}
interface HTMLDataListElement extends HTMLElement {}
interface HTMLDivElement extends HTMLElement {}
interface HTMLDListElement extends HTMLElement {}
interface HTMLFieldSetElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadingElement extends HTMLElement {}
interface HTMLHeadElement extends HTMLElement {}
interface HTMLHRElement extends HTMLElement {}
interface HTMLIFrameElement extends HTMLElement {}
interface HTMLImageElement extends HTMLElement {}
interface HTMLModElement extends HTMLElement {}
interface HTMLLegendElement extends HTMLElement {}
interface HTMLLIElement extends HTMLElement {}
interface HTMLOListElement extends HTMLElement {}
interface HTMLOptGroupElement extends HTMLElement {}
interface HTMLParagraphElement extends HTMLElement {}
interface HTMLPreElement extends HTMLElement {}
interface HTMLSpanElement extends HTMLElement {}
interface HTMLTemplateElement extends HTMLElement {}
interface HTMLTableSectionElement extends HTMLElement {}
interface HTMLTableDataCellElement extends HTMLElement {}
interface HTMLTextAreaElement extends HTMLElement {}
interface HTMLTableSectionElement extends HTMLElement {}
interface HTMLTableHeaderCellElement extends HTMLElement {}
interface HTMLTableSectionElement extends HTMLElement {}
interface HTMLTitleElement extends HTMLElement {}
interface HTMLTableRowElement extends HTMLElement {}
interface HTMLUListElement extends HTMLElement {}

interface SVGSVGElement extends SVGElement {}
interface SVGCircleElement extends SVGElement {}
interface SVGClipPathElement extends SVGElement {}
interface SVGDefsElement extends SVGElement {}
interface SVGDescElement extends SVGElement {}
interface SVGEllipseElement extends SVGElement {}
interface SVGFEBlendElement extends SVGElement {}
interface SVGFEColorMatrixElement extends SVGElement {}
interface SVGFEComponentTransferElement extends SVGElement {}
interface SVGFECompositeElement extends SVGElement {}
interface SVGFEConvolveMatrixElement extends SVGElement {}
interface SVGFEDiffuseLightingElement extends SVGElement {}
interface SVGFEDisplacementMapElement extends SVGElement {}
interface SVGFEDistantLightElement extends SVGElement {}
interface SVGFEDropShadowElement extends SVGElement {}
interface SVGFEFloodElement extends SVGElement {}
interface SVGFEFuncAElement extends SVGElement {}
interface SVGFEFuncBElement extends SVGElement {}
interface SVGFEFuncGElement extends SVGElement {}
interface SVGFEFuncRElement extends SVGElement {}
interface SVGFEGaussianBlurElement extends SVGElement {}
interface SVGFEImageElement extends SVGElement {}
interface SVGFEMergeElement extends SVGElement {}
interface SVGFEMergeNodeElement extends SVGElement {}
interface SVGFEMorphologyElement extends SVGElement {}
interface SVGFEOffsetElement extends SVGElement {}
interface SVGFEPointLightElement extends SVGElement {}
interface SVGFESpecularLightingElement extends SVGElement {}
interface SVGFESpotLightElement extends SVGElement {}
interface SVGFETileElement extends SVGElement {}
interface SVGFETurbulenceElement extends SVGElement {}
interface SVGFilterElement extends SVGElement {}
interface SVGForeignObjectElement extends SVGElement {}
interface SVGGElement extends SVGElement {}
interface SVGImageElement extends SVGElement {}
interface SVGLineElement extends SVGElement {}
interface SVGLinearGradientElement extends SVGElement {}
interface SVGMarkerElement extends SVGElement {}
interface SVGMaskElement extends SVGElement {}
interface SVGMetadataElement extends SVGElement {}
interface SVGPathElement extends SVGElement {}
interface SVGPatternElement extends SVGElement {}
interface SVGPolygonElement extends SVGElement {}
interface SVGPolylineElement extends SVGElement {}
interface SVGRadialGradientElement extends SVGElement {}
interface SVGRectElement extends SVGElement {}
interface SVGStopElement extends SVGElement {}
interface SVGSwitchElement extends SVGElement {}
interface SVGSymbolElement extends SVGElement {}
interface SVGTextElement extends SVGElement {}
interface SVGTextPathElement extends SVGElement {}
interface SVGTSpanElement extends SVGElement {}
interface SVGUseElement extends SVGElement {}
interface SVGViewElement extends SVGElement {}
